### ISSUE TITLE
merge_peft_adapter

### ISSUE THREAD

**Issue by BUILDERlym** [koa-fin/sep#1]
Hi, when I tried to run the examples, a issus appeared in
`model = PeftModel.from_pretrained(model, peft_model_id)` in _merge_peft_adaper.py_
![image](https://github.com/koa-fin/sep/assets/71302160/f62d9012-d46b-4fbc-89ce-60d674c893b0)

**Comment by sia-watsonlee** [comment]
Hello , make sure to install the right version of peft  in requirements.txt. i think that would solve the problem.

**Comment by BUILDERlym** [comment]
> Hello , make sure to install the right version of peft in requirements.txt. i think that would solve the problem.

I think it worked. But when i ran on RTX8000, it always cast OOM at _ppo_trainer.step_. When I tried to run on two gpus, _trainer.train_ in _supervised_fintune_ would cause an error as follows

> File "/miniconda3/envs/sep/lib/python3.11/site-packages/torch/nn/functional.py", line 3059, in cross_entropy
>     return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
>            
> RuntimeError: CUDA error: device-side assert triggered
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Did you run the exp on multi gpus?

**Comment by koa-fin** [comment]
Yes, we did run the exp on multi gpus.

Did you check if your packages are the same versions as those in _requirements.txt_?
If I remember correctly, only specific versions of _transformers_ and _peft_ can work with the current codebase.

**Comment by BUILDERlym** [comment]
> Yes, we did run the exp on multi gpus.
> 
> Did you check if your packages are the same versions as those in _requirements.txt_? If I remember correctly, only specific versions of _transformers_ and _peft_ can work with the current codebase.

thanks, i think it's PyTorch version, solved by setting as _requirements.txt_
